#!/bin/ksh
#
# Shellscript, Build Standard Postprocessing Routine for DDL-Deploy
# Übergaben:   Application ADOit Shortcut


set +x     #zeigt in einer Kornshell die einzelnen Befehle mit Variableninhalt an

SHORTCUT=$1
SHORTCUT=$( echo "$SHORTCUT" | tr '[:lower:]' '[:upper:]' )

if [ $# -ne 1 ]  
   then echo "Das Anwendungskürzel muss spezifiziert werden!"
        echo ""
        echo "Sample: ORAddlDeploy_postproc xxx"
        echo ""
        exit 1
fi

cd /oranfs/share/ora_admin/DDLdeploy_postproc
FILENAME=BV${SHORTCUT}ADM.postproc
RC=0

if [ ! -s ${FILENAME} ]
then
   echo "/oranfs/share/ora_admin/DDLdeploy_postproc/${FILENAME} soll erstellt werden? (y/n)"; read CONFIRM
   CONFIRM=`echo $CONFIRM|tr [a-z] [A-Z]`
   if [ $CONFIRM = 'Y' ]
   then
#      echo "set define on;                                                                             " >${FILENAME}
#      echo "set trimspool on ;                                                                         " >>${FILENAME}
#      echo "SPOOL OFF;                                                                                 " >>${FILENAME}
#      echo "set echo on;                                                                               " >>${FILENAME}
#      echo "set serveroutput on;                                                                       " >>${FILENAME}
      echo "--*****************************************************************************************" >>${FILENAME}
      echo "--  Create Synonyms:                                                                       " >>${FILENAME}
      echo "--*****************************************************************************************" >>${FILENAME}
      echo "--                      <Owner>    <Schema>                                                " >>${FILENAME}
      echo "execute create_synonym('BV"${SHORTCUT}"USR','BV"${SHORTCUT}"ADM') ;                        " >>${FILENAME}
      echo "                                                                                           " >>${FILENAME}
      echo "--*****************************************************************************************" >>${FILENAME}
      echo "-- Set Standard Authotizations:                                                            " >>${FILENAME}
      echo "--*****************************************************************************************" >>${FILENAME}
      echo "execute GRANT_2_STDROLE_RW('BV"${SHORTCUT}"ADM','BV$"${SHORTCUT}"_RW') ;                   " >>${FILENAME}
      echo "execute GRANT_2_STDROLE_RO('BV"${SHORTCUT}"ADM','BV$"${SHORTCUT}"_RO') ;                   " >>${FILENAME}
      echo "                                                                                           " >>${FILENAME}
      echo "--*****************************************************************************************" >>${FILENAME}
      echo "-- Set special Authorizations:                                                             " >>${FILENAME}
      echo "--*****************************************************************************************" >>${FILENAME}
      echo "Standard Post-Processing File for Schema 'BV"${SHORTCUT}"ADM' created successfully."
   else
     echo "*** Keine Aktion durchgeführt, CONFIRM=N ***"
   fi
else
   echo "Standard Post-Processing File for Schema 'BV"${SHORTCUT}"ADM' allready exists - nothing done !"
   RC=1
fi

exit ${RC}