#!/bin/ksh
#
# Shellscript, Execute SQL-Script from file(s) and write to Log.
#              files from given INPDIR with filename like "rc*"
# Übergaben:   Oracle Database
#              Umgebung (K?,F?,I,P)
#              file directory
#              filename prefix (optional)
set +x     #zeigt in einer Kornshell die einzelnen Befehle mit Variableninhalt an

INPDIR=$1
NEWFILEPREF=$2
NEWFILEPREF=$( echo "${NEWFILEPREF}" | tr '[:upper:]' '[:lower:]' )

if [ $# -ne 2 ]  
   then echo "Es müssen beide Parameter (Directory und File-Prefix) spezifiziert werden!"
        echo ""
        echo "Sample: ORAddlDeploy_pfx /oranfs/share/ora_admin/DDL/Vn.nn rcnnn"
        echo ""
        exit 1
   else
        if ! [ -d $1 ]
           then echo "Parameter 1 muss ein gültiges Directory sein!"
           exit 1
        fi
fi

cd ${INPDIR}
RC=0

echo "Alle Dateien im Verzeichnis '${INPDIR}',die nicht 'rc*' heissen werden renamed? (y/n)"; read CONFIRM

CONFIRM=`echo $CONFIRM|tr [a-z] [A-Z]`
if [ $CONFIRM = 'Y' ]
   then
     ## Loop through files prefixed by "rc":------------------------------------------
     for FILENAME in $(find . -maxdepth 1 -type f|grep -v 'rc')
     do
     FILENAME=`basename $FILENAME`
     mv $FILENAME ${NEWFILEPREF}_$FILENAME
     echo "Renamed: $FILENAME nach ${NEWFILEPREF}_$FILENAME"
     done
   else
     echo "*** Rename wurde NICHT durchgeführt, CONFIRM=N ***"
fi

exit ${RC}
