#!/bin/ksh
# @(#) ================================================================================================================
# @(#) File        : ORAr2iRunDDL
# @(#) Author      : Dieter Smets
# @(#) Modified    :
# @(#)
# @(#) Description : This script executes following Steps of the Refresh_2_I Process
# @(#)               - (DDL) generate and execute DDL Files of Versions that have been overwritten from Production
# @(#)
# @(#) Parameters  : - Szenario Name of Process
# @(#)
# @(#) Version     : 1.1
# @(#) Datum       : 09.04.2024
# @(#)
# @(#) Presumption :
# @(#)
# @@(#)  Change History:
# @@(#)
# @@(#)  0.1  2023-08-10  Smets       Created
# @@(#)  0.2  2023-08-26  Smets       "sh ./generated_files/ORAr2iRunDDL.list" aktiviert
# @@(#)  1.0  2024-03-15  Smets       Ermittlung der durchzufuehrenden DDL Deploys korrigieren (TADBA-6093)
# @@(#)  1.1  2024-04-09  MPils       Added "" for Oracle Password
# @(#) ================================================================================================================

R2IDIR=/oranfs/share/ora_admin/DataPump/r2i


SZENARIO=$1
SZENARIO=$( echo "$SZENARIO" | tr '[:upper:]' '[:lower:]' )
DATABASE=DBA-P

cd ${R2IDIR}/${SZENARIO}
RC=0

# Get Password from PasswordFile:
#PASSFILE=/oranfs/share/ora_admin/dbapwd/.orapwd
#DBAUSER=BVBTCUSR
#set +x     # suppress PWD listing
#DBAPASS=$(awk -v u=$DBAUSER '$1==u {print $2}' $PASSFILE)
XONOFF=$(set -o | awk '/^xtrace/ {print $2}')             # xtrace Zustand sichern
PWDDIR=/app/oracle/admin/etc/pwddir
DBAUSER=BVBTCUSR
set +x                                                    # xtrace wg. Password ausschalten
source $PWDDIR/.pwdfile_db_bvbtcusr
DBAPASS=${PWDBVBTCUSR}
if [ $XONOFF == "on" ] ; then set -x ; else set +x ; fi   # xtrace Zustand wiederherstellen

#--- Execute: -------------------------------------------------------------------
SYSOUT=./generated_files/ORAr2iRunDDL.log
rm -f ${SYSOUT}

set +x                                                    # xtrace wg. Password ausschalten
echo "Suppressed: sqlplus ${DBAUSER}/XXXXXXXX@${DATABASE}"

###sqlplus ${DBAUSER}/"${DBAPASS}"@${DATABASE} @../ORAr2iRunDDL.sql ${SZENARIO} > ${SYSOUT} 2>&1
(
sqlplus -s ${DBAUSER}/"${DBAPASS}"@${DATABASE} <<EOSQL
  set pages 0 ;
  set termout off ;
  set echo off ;
  set verify off ;
  set heading off ;
  SET FEEDBACK OFF ;
  set trim off
  set define on;
  SET LINESIZE 120 ;
  SPOOL OFF ;
  SPOOL generated_files/ORAr2iRunDDL.list;
  select 'RC=0' from dual ;

  SELECT DEPLOY_CMD || ' ||let RC=$RC+$?'
    FROM BVDBS.R2I_DDLDEPLOY_CURRENT
   WHERE SZENARIO LIKE '${SZENARIO}%'
   ORDER BY 1;

  select 'exit ${RC}' from dual ;
  exit;
EOSQL
) > ${SYSOUT}
RC=$?
if [  $RC -ne 0 ]
   then
     echo "*************************************************************"
     echo "* Fehler bei SQL Ausfuehrung!"
     echo "* Siehe ${SYSOUT}"
     echo "* RC=$RC"
     echo "*************************************************************"
     RC=1
     exit ${RC}
fi

#Test: exit 0

if test -s "generated_files/ORAr2iRunDDL.list"
then
#
  sh ./generated_files/ORAr2iRunDDL.list
#
#echo "Hier wuerden die DDL-Deploys laufen, jetzt auskommentiert !!!!!!!!"
  RC=$?
  exit ${RC}
else
  echo 'Datei nicht vorhanden oder leer!'
fi

exit 0
