/* ***********************************************************************
**
** Quest Software GmbH
**
** Autor: Johannes Ahrends
*************************************************************************/
SET VERIFY OFF
--SET ECHO OFF
SPOOL create_basis.log
SELECT tablespace_name
  FROM dba_tablespaces;
ACCEPT DEFTS CHAR PROMPT  'Bitte Default Tablespace eingeben fuer Benutzer der Basisdaten angeben: '
ACCEPT STAMM CHAR PROMPT  'Bitte Schemanamen fuer Basisdaten angeben (VORSICHT: das Schema wird gelöscht!): '

DROP USER &stamm. CASCADE
/
CREATE USER &stamm.
IDENTIFIED BY &stamm.
DEFAULT TABLESPACE &defts
/
GRANT CONNECT, DBA TO &stamm.
/
GRANT CREATE PUBLIC SYNONYM TO &stamm.
/
ALTER SESSION SET CURRENT_SCHEMA = &STAMM.;
Prompt Table NACHNAMEN;
CREATE TABLE NACHNAMEN
(
  NACHNAMENNR  NUMBER(10),
  NACHNAME     VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Table ORTE;
CREATE TABLE ORTE
(
  ORTEID   NUMBER(10),
  PLZ      VARCHAR2(8 CHAR),
  ORT      VARCHAR2(50 CHAR),
  BLID     NUMBER(2),
  VORWAHL  VARCHAR2(7 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Table STRASSEN;
CREATE TABLE STRASSEN
(
  STRASSENNR  NUMBER(10),
  STRASSE     VARCHAR2(50 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Table VORNAMEN;
CREATE TABLE VORNAMEN
(
  VORNAMENNR  NUMBER(10),
  ANREDE      VARCHAR2(5 CHAR),
  VORNAME     VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

Prompt Table PERSONENBILDER;
CREATE TABLE PERSONENBILDER
(
  PERSBILDID  NUMBER(10),
  BILD        BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

Prompt Index PERSONENBILDER_PK;
CREATE UNIQUE INDEX PERSONENBILDER_PK ON PERSONENBILDER
(PERSBILDID)
LOGGING
NOPARALLEL
/

Prompt Non-Foreign Key Constraints on Table PERSONENBILDER;
ALTER TABLE PERSONENBILDER ADD (
  CONSTRAINT PERSONENBILDER_PK
 PRIMARY KEY
 (PERSBILDID))
/

Prompt Table EMAILPROVIDER;
CREATE TABLE EMAILPROVIDER (
  PROVIDERID NUMBER,
  provider VARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

CREATE UNIQUE INDEX EMAILPROVIDER_PK ON EMAILPROVIDER
(PROVIDERID)
LOGGING
NOPARALLEL
/

GRANT SELECT ON NACHNAMEN TO PUBLIC
/

GRANT SELECT ON VORNAMEN TO PUBLIC
/

GRANT SELECT ON STRASSEN TO PUBLIC
/

GRANT SELECT ON ORTE TO PUBLIC
/

GRANT SELECT ON PERSONENBILDER TO PUBLIC
/

GRANT SELECT ON EMAILPROVIDER TO PUBLIC
/

DROP PUBLIC SYNONYM NACHNAMEN
/

CREATE PUBLIC SYNONYM NACHNAMEN FOR NACHNAMEN
/

DROP PUBLIC SYNONYM VORNAMEN
/

CREATE PUBLIC SYNONYM VORNAMEN FOR VORNAMEN
/

DROP PUBLIC SYNONYM STRASSEN
/

CREATE PUBLIC SYNONYM STRASSEN FOR STRASSEN
/

DROP PUBLIC SYNONYM ORTE
/

CREATE PUBLIC SYNONYM ORTE FOR ORTE
/

DROP PUBLIC SYNONYM PERSONENBILDER
/

CREATE PUBLIC SYNONYM PERSONENBILDER FOR PERSONENBILDER
/

DROP PUBLIC SYNONYM EMAILPROVIDER
/

CREATE PUBLIC SYNONYM EMAILPROVIDER FOR EMAILPROVIDER
/

PROMPT Datensaetze werden eingefuegt ...
SET TERMOUT OFF
set echo off
set feedback off
@@insert_orte
@@insert_vornamen
@@insert_nachnamen
@@insert_strassen
@@insert_emailprovider
COMMIT;
SPOOL OFF
PROMPT Als letztes bitte die Bilder ueber imp importieren

