#!/bin/bash
# ================================================================================================================
#  File        : ORAcheck_mk
#  Author      : Thorsten Thiel
#  Modified    :
#
#  Description : This script does all the stuff to implement a basic monitoring with check_mk.
#                Je nach Anforderung (del|add) , werden die Links fuer die DB-Spezifischen CheckScripte erstellt
#                oder geloescht. Es wird eine entsprechende Anforderungsmail an die Gruppe Systemmanagement
#                abgeschickt.
#
#  Version     : 1.0
#
#  Attention   : This script must be started as user oracle
#
#  Change History:
#
#    1.0  2013-06-18  Th. Thiel                        Created
#
# ----------------------------------------------------------------------------------------------------------------
#set -x
#-----------------------------------------------------------------------------------------------------------------
#     Global script environment
#-----------------------------------------------------------------------------------------------------------------
MAILTO="sysmgt\@barmenia.de,unix-dba\@barmenia.de"
#MAILTO="thorsten.thiel\@barmenia.de"
HOST=`hostname -s`
LONGHOST=`hostname -f`
SCRIPTNAME=$(basename $0)
SCRIPTSHORTDESC="implement a basic monitoring with check_mk"
ORACLE_BASE="/app/oracle"
SCRIPTPATH="/app/oracle/bin"
FUNCTIONSFILE="${SCRIPTPATH}/.bash_functions"
LOGDIR="/app/logs"
LOGFILE="${LOGDIR}/${SCRIPTNAME}_`date +%Y%m%d%H%M%S%N`.log"
NAG_CHK_SCRIPTS_DIR="/app/oracle/bin/nagios"
NAG_CHK_SCRIPTS="check_arclog_amount.sh check_maint_task_win_hung.sh check_tbsp_usage.sh"

source $FUNCTIONSFILE
RC=$?
if [ $RC -ne 0 ]; then
 echo "${FUNCTIONSFILE} file not found!"
 exit $RC
fi

#-----------------------------------------------------------------------------------------------------------------
#     FUNCTION: Help routine
#-----------------------------------------------------------------------------------------------------------------
function usage()
{
echo ""
echo "  Command     : $SCRIPTNAME"
echo "  Description : $SCRIPTSHORTDESC"
echo ""
echo "  Parameters:   -act,                     Action (ADD|DEL)"
echo "                -sid,                     Database Name "
echo ""
echo "  Example     : ORAcheck_mk -act add -sid WHATSID"
echo ""
echo "  Attention   : This script must be started as user oracle"
echo ""
exit
}

#-----------------------------------------------------------------------------------------------------------------
#     Check if user is not oracle, otherwise abort   
#-----------------------------------------------------------------------------------------------------------------
if [ `id -un` != "oracle" ]; then
  Bmsg -rm "Script may not run as user `id -un`, it must be started and run as user oracle!"
  RC=255
  Bmsg -rm "Error Code: ${RC}"
  exit $RC
fi

#-----------------------------------------------------------------------------------------------------------------
#     Get Parameter
#-----------------------------------------------------------------------------------------------------------------
while true; do
  case "$1" in
    -act | --action ) ACTION="$2";act=1; shift 2 ;;
    -sid | --oracle_sid ) ORACLE_SID="$2";sid=1; shift 2 ;;
    -h | --help ) usage ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

#-----------------------------------------------------------------------------------------------------------------
#     test to see if they gave the option
#-----------------------------------------------------------------------------------------------------------------
if [ "x" == "x$sid" ]; then
  echo ""
  Bmsg -rm "-sid | --oracle_sid [option] is required"; echo ""; usage
fi

if [ "x" == "x$act" ]; then
  echo ""
  Bmsg -rm "-act | --action [option] is required"; echo ""; usage
fi

#-----------------------------------------------------------------------------------------------------------------
#     FUNCTION: any functions
#-----------------------------------------------------------------------------------------------------------------
check_nag_logdir()
{
NAG_LOG_DIR="/app/oracle/admin/log/nagios"
if [ ! -d $NAG_LOG_DIR ]
then
   Bmsg -r -m "Das Logverzeichnis $NAG_LOG_DIR existiert nicht!"
   mkdir -p /app/oracle/admin/log/nagios
   RC=$?
   if [ $RC -ne 0 ]
   then
      Bmsg -r -m "Das Logverzeichnis $NAG_LOG_DIR konnte nichtangelegt werden!"
      exit $RC
   else
      Bmsg -g -m "Das Logverzeichnis $NAG_LOG_DIR wurde angelegt!"
   fi
fi
}

check_nag_chk_script()
{
if [ ! -s $NAG_CHK_SCRIPTS_DIR/$SCRIPT ]
then
   rsyncbin
   if [ ! -s $NAG_CHK_SCRIPTS_DIR/$SCRIPT ]
   then
      Bmsg -r -m "Das Check-Script >$NAG_CHK_SCRIPTS_DIR/$SCRIPT< fehlt!"
      exit 1
   fi
fi
}

add_nag_chk_script_lnk()
{
SCRIPT_LNK="`basename $SCRIPT .sh`_${ORACLE_SID_UC}.sh"
if [ ! -s $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK ]
then
   ln -s $NAG_CHK_SCRIPTS_DIR/$SCRIPT $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK
   RC=$?
   if [ $RC -eq 0 ]
   then
      Bmsg -g -m "Link $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK wurde angelegt"
      SCRIPT_MONI_ANF="$SCRIPT_MONI_ANF $SCRIPT_LNK"
   else
      Bmsg -r -m "Link $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK konnte nicht angelegt werden!"
      exit $RC
   fi
else
   Bmsg -g -m "Link $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK existiert schon"
fi
}

del_nag_chk_script_lnk()
{
SCRIPT_LNK="`basename $SCRIPT .sh`_${ORACLE_SID_UC}.sh"
if [ -s $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK ]
then
   unlink $SCRIPT_LNK
   RC=$?
   if [ $RC -eq 0 ]
   then
      Bmsg -g -m "Link $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK wurde entfernt"
      SCRIPT_MONI_ANF="$SCRIPT_MONI_ANF $SCRIPT_LNK"
   else
      Bmsg -r -m "Link $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK konnte nicht entfernt werden!"
      exit $RC
   fi
else
   Bmsg -r -m "Link $NAG_CHK_SCRIPTS_DIR/$SCRIPT_LNK existiert nicht!"
fi
}

mail2sysmgt()
{
Bmsg -m " "
if [ "$ACTION_UC" == "ADD" ]
then
cat <<EOM|mail -s "Monitoringanforderung auf $HOST fuer $ORACLE_SID_UC" $MAILTO
Hallo!
Bitte richten Sie auf der $HOST ein Monitoring fuer die Datenbank $ORACLE_SID_UC ein!
Es sollen folgende Check-Scripte ausgefuehrt werden:

$SCRIPT_MONI_ANF

Mit kollegialen Gruessen

DB-Administratoren
Team IT-DB/Change
Datenbankadministration
Tel. 3745
EOM
RC=$?
elif [ "$ACTION_UC" == "DEL" ]
then
cat <<EOM|mail -s "Monitoring auf $HOST fuer $ORACLE_SID_UC beenden" $MAILTO
Hallo!
Bitte das Monitoring der Datenbank $ORACLE_SID_UC auf der $HOST beenden!
Folgende Check-Scripte sollen nicht mehr ausgefuehrt werden:

$SCRIPT_MONI_ANF

Mit kollegialen Gruessen

DB-Administratoren
Team IT-DB/Change
Datenbankadministration
Tel. 3745
EOM
RC=$?
fi
if [ $RC -eq 0 ]
then
   Bmsg -g -m "Monitoringanforderung an $MAILTO versandt"
else
   Bmsg -r -m "Monitoringanforderung an $MAILTO konnte nicht versendet werden!"
fi
}

#-----------------------------------------------------------------------------------------------------------------
#     Set Environment
#-----------------------------------------------------------------------------------------------------------------
ACTION_UC=`echo $ACTION|tr 'a-z' 'A-Z'`
ORACLE_SID_UC=`echo $ORACLE_SID|tr 'a-z' 'A-Z'`
ORACLEHOME=`grep "^${ORACLE_SID_UC}" /etc/oratab|awk -F ":" ' { print $2 }'`

#-----------------------------------------------------------------------------------------------------------------
#     Main program - start
#-----------------------------------------------------------------------------------------------------------------
Bscriptstart "${SCRIPTNAME} - ${SCRIPTSHORTDESC}"

Bmsg -m " "; Bmsg -g -m "### Database Instance $ORACLE_SID_UC ###"
if [ "$ACTION_UC" == "ADD" ]; then
  check_nag_logdir
  for SCRIPT in $NAG_CHK_SCRIPTS
  do
     check_nag_chk_script
     add_nag_chk_script_lnk
  done
fi

if [ "$ACTION_UC" == "DEL" ]; then
  for SCRIPT in $NAG_CHK_SCRIPTS
  do
     del_nag_chk_script_lnk
  done
fi

if [ "$SCRIPT_MONI_ANF" != "" ]
then
   mail2sysmgt
fi
Bmsg -m " "

#-----------------------------------------------------------------------------------------------------------------
#     Main program - end
#-----------------------------------------------------------------------------------------------------------------
Bscriptend 
exit
