#!/bin/bash
# @(#) ================================================================================================================
# @(#) File        : ORAswitchover
# @(#) Author      : Johannes Ahrends
# @(#)
# @(#) Version     : 0.3
# @(#) Date        : 09.04.2024
# @(#)
# @(#) Description : Switchover Dataguard Database
# @(#)
# @(#) Syntax      : see usage (ORAswitchover -h)
# @(#)
# @(#) Attention   : This script can be started with any user as long as ORACLE_HOME and PATH are set
# @(#)
# @(#) Presumption :
# @(#) 1. Primary and Standby Database are both up and running
#
# @@(#) Change History:
# @@(#)
# @@(#) 0.1     22.03.2016 J. Ahrends basic script
# @@(#) 0.2     25.01.2018 M. Pils    changed pwddir location
# @@(#) 0.3     09.04.2024 M. Pils    Added "" for Oracle Password
# @(#) ================================================================================================================
#
# Variables
#
SCRIPTDIR=/app/oracle/bin
PWDDIR=/app/oracle/admin/etc/pwddir
DATE=`date +%Y-%m-%d-%H-%M-%S`
RT=0
#
#-----------------------------------------------------------------------
#
#Functions
#
#-----------------------------------------------------------------------
#
#-----------------------------------------------------------------------
# Usage help
#-----------------------------------------------------------------------
#
usage() {
   echo " "
   echo "Function:  Create standby database from primary database"
   echo " "
   echo "     Usage:  `basename $0` -s <dbname> [-h]"
   echo "        -d:  database unique name to become new primary"
   echo "        -h:  this help"
   echo " "
   echo " Example: $0 -s DG12C_S2"
}
#
#-----------------------------------------------------------------------
# Logger Script
#-----------------------------------------------------------------------
#
logger() {
if [ -r $SCRIPTDIR/log4sh ]
then
   LOCALLOGGER="`basename $0 | cut -d"." -f 1`_log4sh.properties"
   if [ -r $SCRIPTDIR/${LOCALLOGGER} ]
   then
      LOG4SH_CONFIGURATION=$SCRIPTDIR/$LOCALLOGGER . $SCRIPTDIR/log4sh
   else
      LOG4SH_CONFIGURATION=$SCRIPTDIR/log4sh.properties . $SCRIPTDIR/log4sh
   fi
else
   echo "ERROR: could not load (log4sh)" >&2
   exit 1
fi
#  echo "LOG4SH_CONFIGURATION:$LOG4SH_CONFIGURATION"
}
#
#-----------------------------------------------------------------------
# Read password from hidden file
#-----------------------------------------------------------------------
#
readPWD() {
   logger_debug "SYS Password"
   if [ -f $PWDDIR/.pwdfile_db_sys ]
   then
      typeset -l ORACLE_SID_LC=$PRIMARYDB
      source $PWDDIR/.pwdfile_db_sys
      sysPW=$PWDSYS
      logger_debug "Password = ${sysPW}"
   else
      logger_error "No Passwordfile"
      exit 1
   fi
}
#
#-----------------------------------------------------------------------
# Check if Configuration is ready to use
#-----------------------------------------------------------------------
#
checkDG() {
   logger_info "Check Dataguard Broker Configuration"
   RT=$(dgmgrl / <<EOVER
   show configuration
EOVER
)
   logger_debug $RT
   if [ `echo $RT| grep -c ERROR` -ne 0 ]
   then
      logger_error "Dataguard Configuration not successful"
      logger_error $RT
      exit 2
   else
      logger_info "Dataguard configuration successful"
   fi
}
#
#-----------------------------------------------------------------------
# Check if Database is already primary
#-----------------------------------------------------------------------
#
isPrimary()
{
   ROLE=$(sqlplus -s sys/"${sysPW}"@$DBUNAME as sysdba <<EOPRIM
      set heading off
      SELECT decode(database_role,'PRIMARY',0,1) FROM v\$database;
EOPRIM
)
   logger_debug "ROLE = $ROLE"
   if [ $ROLE -eq 0 ]
   then
      logger_error "Database $DBUNAME is already Primary Database"
      exit 3
   fi
}

#
#-----------------------------------------------------------------------
# Switchover
#-----------------------------------------------------------------------
#
switchOver() {
   logger_info "Dataguard Switchover"
   RT=$(dgmgrl / <<EOVER
   switchover to '${DBUNAME}'
EOVER
)
   if [ `echo $RT| grep -c ERROR` -ne 0 ]
   then
      logger_error "Switchover NOT successful"
      logger_error $RT
      exit 21
   else
      logger_info "Switchover successful"
   fi
}

#-----------------------------------------------------------------------
#
# Main
#
#-----------------------------------------------------------------------

if [ $# -eq 0 ]
then
   usage
   exit
fi
logger
#
# Read Parameter
#
while [ $# -gt 0 ]
do
   option="$1"
   case $option in
      -d|--databaseuname)
         DBUNAME="$2"
         shift
         ;;
      -h|--help)
         usage
         exit
         ;;
       *)
         usage
         exit
         ;;
   esac
   shift
done
if [ -z "$DBUNAME" ]
then
   logger_fatal "Variable DBUNAME not set!"
   usage
   exit 1
fi

#
logger_debug "1. Read Sys Password"
readPWD


logger_debug "2. Check Dataguard Configuration"
checkDG

logger_debug "3. Check if $DBUNAME is already Primary"
isPrimary

logger_debug "4. Switchover to $DBUNAME"
switchOver

sleep 60
logger_debug "5. Check Dataguard Configuration"
checkDG
